# Generated by Django 2.1.7 on 2019-03-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dictionary_translation',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], max_length=2)),
            ],
            options={
                'db_table': 'dictionary_word',
            },
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'language')},
        ),
        migrations.AddField(
            model_name='translation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='dictionary.Word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated', to='dictionary.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('source', 'translated')},
        ),
    ]
