# Generated by Django 2.2.5 on 2019-11-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_example',
            },
        ),
        migrations.CreateModel(
            name='RecordingModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('audio_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_recording',
            },
        ),
        migrations.CreateModel(
            name='SynonymModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_synonym',
            },
        ),
        migrations.CreateModel(
            name='TranslationExampleModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_translation_example',
            },
        ),
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('usage_notes', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_translation',
            },
        ),
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], max_length=2)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'noun'), (2, 'adverb'), (3, 'adjective'), (5, 'verb'), (4, 'pronoun'), (6, 'preposition'), (7, 'conjunction'), (8, 'interjection'), (9, 'idiom'), (10, 'phrasal verb'), (11, 'prefix'), (12, 'phrase'), (13, 'sentence'), (14, 'suffix')], default=0)),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_entry',
                'unique_together': {('text', 'language', 'type', 'source_url')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.entrymodel',),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.examplemodel',),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.recordingmodel',),
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.synonymmodel',),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.translationmodel',),
        ),
        migrations.CreateModel(
            name='TranslationExample',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lang.translationexamplemodel',),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_subjects', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_objects', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='translationexamplemodel',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_translations', to='lang.Example'),
        ),
        migrations.AddField(
            model_name='translationexamplemodel',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_examples', to='lang.Translation'),
        ),
        migrations.AddField(
            model_name='synonymmodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_subjects', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='synonymmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_objects', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_subjects', to='lang.Entry'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_objects', to='lang.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='translationmodel',
            unique_together={('object', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='synonymmodel',
            unique_together={('object', 'subject')},
        ),
    ]
