# Generated by Django 2.2.5 on 2019-10-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'noun'), (2, 'adverb'), (3, 'adjective'), (5, 'verb'), (4, 'pronoun'), (6, 'preposition'), (7, 'conjunction'), (8, 'interjection'), (9, 'idiom'), (10, 'phrasal verb'), (11, 'prefix'), (12, 'phrase'), (13, 'sentence'), (14, 'suffix')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='entrymodel',
            unique_together={('text', 'language', 'type', 'url')},
        ),
    ]
