# Generated by Django 2.1.7 on 2019-04-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedEntryData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeated_entries', to='lang.Entry')),
            ],
            options={
                'db_table': 'repeated_entry',
            },
        ),
        migrations.CreateModel(
            name='RepetitionData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repetition',
            },
        ),
        migrations.CreateModel(
            name='RepeatedEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('lang.repeatedentrydata',),
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('lang.repetitiondata',),
        ),
        migrations.AddField(
            model_name='repeatedentrydata',
            name='repetition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeated_entries', to='lang.Repetition'),
        ),
    ]
